### ISSUE TITLE
Convolving with a line spread function

### ISSUE THREAD

**Issue by lwymarie** [rcooke-ast/ALIS#13]
Will there be functionality for convolving an input line profile with the instrument's line spread function? Currently specifying the velocity FWHM at every pixel is possible, but I presume that assumes a Gaussian line-spread function. 

I'd like to make use of linetools' COS and STIS line spread functions.

**Comment by rcooke-ast** [comment]
This already exists, and is a feature in development. See the `lsf` branch for the implementation. I've not tested it for STIS, but I have tested it with COS. Here is an example of how to use it with COS:

`resolution=lsf(name:COS,grating:G130M,life_position:1,cen_wave:1309)`

It will be merged into the master branch soon, but this will get you started for now.

**Comment by lwymarie** [comment]
Thank you! I tested the LSF of COS G136M LP1. It works. 

I will look forward to the future STIS implementation!
