### ISSUE TITLE
Cannot give coverfactor

### ISSUE THREAD

**Issue by lwymarie** [rcooke-ast/ALIS#14]
Error messages are output when I give cover factors to my model. The error messages read
"14N_IV 765.1467 has no q-value. "
eight times, as I have eight components. Then the program hangs. 

My initial model is as follows. 

 absorption
  voigt   ion=14N_IV   14.1000000      1.1290800000RA      30.000000ba      0.0000000E4TA      0.0000000      0.0000000      1.0000        specid=0    
  voigt   ion=14N_IV   14.0000000      1.1295200000RB      27.000000bb      0.0000000E4TA      0.0000000      0.0000000      1.0000        specid=0    
  voigt   ion=14N_IV   13.4000000      1.1301700000RC      27.000000bc      0.0000000E4TA      0.0000000      0.0000000      1.0000        specid=0    
  voigt   ion=14N_IV   14.1000000      1.1304500000RD      20.000000bd      0.0000000E4TA      0.0000000      0.0000000      1.0000        specid=0    
  voigt   ion=14N_IV   13.6000000      1.1308900000RE      15.000000be      0.0000000E4TA      0.0000000      0.0000000      1.0000        specid=0    
  voigt   ion=14N_IV   13.5000000      1.1312700000RF      18.000000bf      0.0000000E4TA      0.0000000      0.0000000      1.0000        specid=0    
  voigt   ion=14N_IV   13.5000000      1.1314900000RG      25.000000bg      0.0000000E4TA      0.0000000      0.0000000      1.0000        specid=0    
  voigt   ion=14N_IV   13.1000000      1.1329900000RH      10.000000bh      0.0000000E4TA      0.0000000      0.0000000      1.0000        specid=0    
 Convolution
  lsf       life_position=1  name=COS  grating=G160M  cen_wave=1623

A side note is that this NIV765 transition is manually added by me to an atomic_marie.xml file. However, I can do Voigt profile fitting as normal and convolve with COS's line spread function on this coverfactor branch. Did I not write my model in a correct format? 

Thanks.

**Comment by lwymarie** [comment]
I figured out. It was another problem. The values for Deltaa/a and Deltamu/mu have to be fixed at zero. 

The line profiles fit well! Closing.

**Comment by rcooke-ast** [comment]
That's one solution, or you can not avoid writing "0.0000000E4TA 0.0000000 0.0000000", and just set the coverfactor parameter to be "coverfactor=1.0000" instead of just writing "1.0000".

A word of caution... coverfactor doesn't actually mean the covering factor when you have multiple lines in your absorption model, as you have. If you're looking to estimate the covering factor of your absorption line, I would ask ALIS to fit for the zero level of the absorption.

**Comment by lwymarie** [comment]
Thanks for the advice. I'll fit zero level.
 
In line 205 of alfunc_voigt.py, it looks like par[6] is one minus partial coverage fraction. May I ask what does coverfactor actually mean in ALIS?

**Comment by rcooke-ast** [comment]
Good question. In the case of a single absorption component, coverfactor should give the same result as zerolevel. However, when there are multiple (blended) components, the covering factor is applied to each individual absorption line, and then multiplied together. For example, if you have a 2 absorption component model (both lines are saturated), and the coverfactor parameter is set to 0.1 for each of them, the model will show a trough at 0.1*0.1=0.01.

As a side note, the model you listed above hasn't tied any of the absorption component covering factors together, which could yield some funny (very degenerate) results.

The main purpose of coverfactor is when you're fitting a single component to a line (originally intended for H I Lya). In most cases, I think the zerolevel functionality is better suited.

**Comment by lwymarie** [comment]
My understanding was that the zero level is a constant offset, like a constant emission. So the final model should be 
(continuum - zerolevel) * (e^-tau) + zerolevel
And so (1 - zerolevel/continuum) is effectively the partial coverage fraction. 

I'm looking at alis.py, line 356. It looks like the final model is 
continuum * (zerolevel + e^-tau) / (continuum + zerolevel)

Would you please explain to me what the zero level does?

**Comment by rcooke-ast** [comment]
You're correct that the partial covering fraction should be `(1 - zerolevel/continuum)`.

Regarding line 356, I need to think about this some more, because I've changed this quite a few times already while testing. Looking at it now, I think it should be:

`mdtmp = mcont[sp][llx:lux]*(mdtmp +  mzero[sp][llx:lux]*(1.0-mdtmp)/mcont[sp][llx:lux])`

Try this line of code and see if this fixes your problem. If so, feel free to submit a PR if you can convince yourself that this is the correct line of code that should replace line 356... I think it might be...

**Comment by lwymarie** [comment]
The zerolevel of my model output was 0.1036, with normalized flux. If I used the coverfactor method instead, I got a coverfactor output of 0.9005. Then I replaced line 356 with the above suggestion. The zerolevel became 0.0938. So they are all close. 

It looks like your suggested replacement means the final model should be continuum * (e^-tau + zerolevel*(1-e^-tau)/continuum). Would you please explain more why the final model should be calculated this way, with regard to the zerolevel placement?

**Comment by rcooke-ast** [comment]
Thanks for the update.

You're reading the code correctly. It is indeed:

`continuum * (e^-tau + zerolevel*(1-e^-tau)/continuum)`

To see why I used this formulation, consider that `e^-tau` can take extreme values of 0 (the zerolevel) and 1 (the continuum). In the case `e^-tau=0`, we have `model=zerolevel`. When `e^-tau=1`, we have `model=continuum`.

The only problem with this formulation is when the continuum is not normalized, and you want to calculate the zerolevel as a _fraction_ of the continuum. I think the current version of the code trys to account for this, but I'll have to go back and decide if this is doing as I would expect. It should be no concern for you though, as your continuum is normalized.

**Comment by lwymarie** [comment]
My idea may be oversimplified, but I'm thinking setting the zero level this way: 
(continuum - zerolevel) * e^-tau + zerolevel
With this formula, for e^-tau = 0, the model recovers the zerolevel, and for e^-tau = 1, the model recovers the continuum. My rationale is that, the zerolevel represents the area of the background emitting source that is not covered, and it is always there regardless of the optical depth thru the absorber. May I know the advantages of using your above formula instead? 

Also how would you recommend handling components with different coverage fractions?

**Comment by rcooke-ast** [comment]
The problem with this approach is that it only works when the continuum is normalized. At the end of the day, you want something which represents the _fraction_ of the continuum level. I'll probably need to think about it some more, but don't have the time to do it at the moment, as I'm on parental leave.
