### ISSUE TITLE
An issue about Voigt profile

### ISSUE THREAD

**Issue by jxcing** [rcooke-ast/ALIS#18]
Hi, Ryan:

Recently, I focus on the absorption line fitting by Voigt profile. I had an issue when I read your code, alfunc_voigt.py. In section 8.15 of the doc, I see the Eq.19:  <a href="https://www.codecogs.com/eqnedit.php?latex=x=\frac{v-v_0}{\Delta&space;v_D}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?x=\frac{v-v_0}{\Delta&space;v_D}" title="x=\frac{v-v_0}{\Delta v_D}" /></a>, where <a href="https://www.codecogs.com/eqnedit.php?latex=\Delta&space;v_D=\frac{b}{\lambda_0}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\Delta&space;v_D=\frac{b}{\lambda_0}" title="\Delta v_D=\frac{b}{\lambda_0}" /></a> in Eq.17.
However, I see `v=wv*ww*((1.0/ww)-(1.0/wv))/bl` in 212th line of alfunc_voigt.py, where `bl=par[2]*wv/2.99792458E5` in 207th line. Then we get `v = ((c/ww)-(c/wv))/(par[2]/ww)`, where c is speed of light 2.998E5. I think the v in code means x in Eq.19 and par[2] is b in Eq.17. The ww in code is <a href="https://www.codecogs.com/eqnedit.php?latex=\lambda" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\lambda" title="\lambda" /></a>, wv is <a href="https://www.codecogs.com/eqnedit.php?latex=\lambda_0" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\lambda_0" title="\lambda_0" /></a>. Therefore, we derive <a href="https://www.codecogs.com/eqnedit.php?latex=x=\frac{v-v_0}{b/\lambda}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?x=\frac{v-v_0}{b/\lambda}" title="x=\frac{v-v_0}{b/\lambda}" /></a> is different from Eq.19.
I think the code in 212th line should be `v=wv**2*((1.0/ww)-(1.0/wv))/bl`

Could you tell me what is wrong with my understanding?
Thank you.

**Comment by rcooke-ast** [comment]
Hi @jxcing - Sorry for my delayed reply... GH issues in ALIS aren't notifying my inbox for some reason - I'll look into it. Basically, you are correct, the main difference is that the code is currently written as:
```
v=(1-lambda/lambda0) / (b/c)
```
while in the manual is is written as:
```
v=(lambda0/lambda - 1) / (b/c)
```
I'll need to look into this some more... I think you might be correct - something in the code might need to be fixed. The code makes the line profile symmetric about lambda0, while the manual makes the line profile symmetric about nu0, and the latter is correct.

**Comment by jxcing** [comment]
Hi, Ryan. Sorry for replying to this so late! I tried the fitting later and the two cases are no different in our project (redshift is around 0). Thank you for your reply.
