### ISSUE TITLE
setup/install

### ISSUE THREAD

**Issue by profxj** [rcooke-ast/ALIS#2]
Would you welcome a PYPIT-like apporach to installation and setup?
Still is fresh in my head so wouldn't take me longer than ~10min to make it so..

**Comment by rcooke-ast** [comment]
By all means!

In fact, there are many improvements that have been made with PYPIT that I
had hoped to add to ALIS. I plan an overhaul of the code when I'm settled
in Durham.

**Comment by profxj** [comment]
Ok.  I’ll probably do this one as it is fresh in my head.
Of course any mistake I’ve made on PYPIT will now
be here too! ;)

> On Jun 27, 2016, at 12:47 PM, Ryan Cooke notifications@github.com wrote:
> 
> By all means!
> 
> In fact, there are many improvements that have been made with PYPIT that I
> had hoped to add to ALIS. I plan an overhaul of the code when I'm settled
> in Durham.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub https://github.com/rcooke-ast/ALIS/issues/2#issuecomment-228854398, or mute the thread https://github.com/notifications/unsubscribe/AD0BjY3wUlEK0VMmutPWFoTn1AFtphmxks5qQCjqgaJpZM4I_ZrR.
> 
> !DSPAM:826,577182f6291361049426601!

---

J. Xavier Prochaska
UCO/Lick Observatory
1156 High St.
UC Santa Cruz
Santa Cruz, CA 95064

http://www.ucolick.org/~xavier/
http://imps.ucolick.org/
http://www.qpqsurvey.org/
http://k1dm3.ucolick.org/
http://www.ucolick.org/~xavier/IDL/index.html
https://github.com/pyigm/pyigm
https://github.com/linetools/linetools

831-459-2135 (Direct)
831-459-2991 (UCO/Lick Main)
831-459-5244 (Fax)

**Comment by rcooke-ast** [comment]
Addressed by PR #3
